### ISSUE TITLE
Awesome ISO issues - can't use pacman

### ISSUE THREAD

**Issue by thatcriticguy** [arcolinuxb/arco-awesome#1]
Tons of issues with the latest Awesome ISO that was just released. I went to update and got a stream of pacman errors, directories missing such as /var/lib/pacman....

This is also happening with the prior awesome iso as well. See screenshot here:
https://imgur.com/a/sYbCmAc

**Comment by arcolinuxz** [comment]
I just installed ArcoLinuxB Awesome Full iso and I am updating without issues
https://imgur.com/d9h2tji

Sounds like you stopped the update of the pacman in the middle and your databases are partially downloaded.

Hence the .part name in the file.

This is how it should look
![awesome](https://user-images.githubusercontent.com/36679406/52901443-e16fc500-3203-11e9-826c-53774a98fc21.png)

Never had this issue but common sense solution would be to delete these broken databases and do an update again.

There might be a command for it but did not come it across.

**Comment by arcolinuxz** [comment]
We use the arcolinux forum to help you out.
